### PR TITLE
Update index.html.erb

### PR DESCRIPTION
**Pull request by alphaRed03**
logo (1)
add on of exchange secureshift

### CODE REVIEW

**Comment by zquestz** [comment]
This PR is incomplete and doesn't include the graphic required.

**Comment by alphaRed03** [comment]
Hello i created the new pull request with  include the graphic required. 
Kindly check.

**Comment by zquestz** [comment]
Sorry we are unable to add this site at this time.

**Comment by alphaRed03** [comment]
Thanks for responding is there any issues over our exchange let us know

**Pull request closed without merging**
