### PR TITLE
Frontend changes

### PR DESCRIPTION
**Pull request by baronsferric**
Okay tidied up my house a bit and moved things into a separate branch to review.  

Changes include:

1. Mobile changes (2 logos side by side)
2. Swapped out logo files for more consistent sizes / dimensions
3. Added hover styles to logos / hrefs
4. Added comparison chart
5. Fixed a bit of typography
6. Added alert in blue for fork notice
7. Added scrollto functionality
8. Added section wrappers

### CODE REVIEW

**Comment by zquestz** [comment]
Like a lot of these changes, but some I am not huge on. I am going to incorporate certain parts immediately, then will discuss the other items with you. Love the new tiles, and the shaded sections!

**Comment by zquestz** [comment]
In the future lets try to limit PR's to one logical layout change and include a screenshot. That way everyone can comment about and see what is going in.

**Comment by baronsferric** [comment]
Sounds good! Sorry about the big batch of changes. Future changes will have more commits to sort through and PRs with screens. 

If there's any specific tasks you'd like me to tackle on the front-end please just let me know.

**Comment by zquestz** [comment]
Closing this PR as it includes a gigantic amount of files for an alternate site. Lets open up PRs per change, that way everyone can see them and vote on inclusion.

**Pull request closed without merging**
