### PR TITLE
Update wallets/exchanges/services to button style

### PR DESCRIPTION
**Pull request by zquestz**
This updates the styles of wallets, exchanges, and services.

exchange-styles

You can also preview it at: https://htmlpreview.github.io/?https://raw.githubusercontent.com/zquestz/bitcoincash/buttons/html/index.html

### CODE REVIEW

**Comment by rawb0t** [comment]
jesus that looks much better

**Comment by schancel** [comment]
This is awesome.  The preview shows up as having unparsed javascript at the end -- but probably it's just github previewing errors.

**Comment by baronsferric** [comment]
Lookin' good!

**Comment by Mengerian** [comment]
Looks good

**Pull request merged**
