### PR TITLE
Green Logos and Visual identity

### PR DESCRIPTION
**Pull request by Ralphive**
I took the liberty to work on some issues mentioned on #45 working on the migration from the old orange logos to the new green ones.

 - I updated the main page logo svg (removing the wings)
- The CSS in general 
- The Logo/Graphics page with files I got from https://bch.info/en/media
- Logo pack to download also include new logos displayed on the graphics page
- Favicon now is green.

Still missing a "donation" green graphics, so I removed the option from the page at this time.

### CODE REVIEW

**Comment by Ralphive** [comment]
Btw, here is how it looks like
* [index](https://user-images.githubusercontent.com/9930965/110350618-cf9c2d00-802b-11eb-965e-882090a1a5cf.png)
* [graphics](https://user-images.githubusercontent.com/9930965/110350669-de82df80-802b-11eb-97b6-6cbf66d5941d.png)


image

**Comment by JeremyEllingham** [comment]
This looks slick, awesome!  I was thinking of doing this but it's already done!

**Comment by Ralphive** [comment]
Thanks, hope @zquestz can merge it.

Looking forward to point people to the new page 👀

**Comment by zquestz** [comment]
This looks great. Would be nice to get more feedback from the community, but I am 100% down with going green!

**Comment by Ralphive** [comment]
Oops
Missed those 
Will fix

**Pull request merged**
