### PR TITLE
Community requests for new service tiles

### PR DESCRIPTION
**Pull request by JeremyEllingham**
Added some documentation because I'm a Docker noob and couldn't figure out how to get changes working for ages.

Updates to Projects tiles as requested by the community on Reddit.

Remove Coinomi: https://www.reddit.com/r/btc/comments/lwej42/pull_requests_pr_welcome_on_bitcoincashorg/gph4e6g/

Add BCH.games to Projects: https://www.reddit.com/r/btc/comments/lwej42/pull_requests_pr_welcome_on_bitcoincashorg/gpj5hqj/

Add various other services: https://www.reddit.com/r/btc/comments/lwej42/pull_requests_pr_welcome_on_bitcoincashorg/gph723h/

Before:

Screen Shot 2021-03-09 at 22 35 37

After:

Screen Shot 2021-03-09 at 23 22 45

### CODE REVIEW

**Comment by zquestz** [comment]
This looks great, but we should re-order these tiles. Lets get cashfusion, memo, noise, etc near the front. Some of the ones that were there aren't very active and we want to show the best stuff first!

**Comment by JeremyEllingham** [comment]
Ordering pretty arbitrary but I moved up some of the more active ones that I know have been doing things in the scene recently.

**Comment by zquestz** [comment]
This looks fantastic. Thanks for the contribution!

**Comment by JeremyEllingham** [comment]
Haha after more than an hour of chopping and editing those .png files I was a bit over it, but yeah I agree the member.cash one could be made a little nicer.

**Comment by coinomiAngelos** [comment]
Hey @zquestz why the removal? Coinomi was the first multiasset wallet to support BCH in August 17, with one click claim for the fork. Has been updating religiously since whenever needed. We're currently running BCHN. Please advise.

Angelos from Coinomi

**Comment by zquestz** [comment]
Sorry didn't notice it was removed. Definitely can be added back!

**Comment by coinomiAngelos** [comment]
> Sorry didn't notice it was removed. Definitely can be added back!

Appreciated! Latest logo (as the one I found in this repo is the old one) are at: https://downloads.coinomi.com/files/Coinomi-Brand-Assets.zip

**Comment by zquestz** [comment]
Can you post a PR?

**Comment by coinomiAngelos** [comment]
Absolutely, coming in a bit. Thanks again!

**Comment by coinomiAngelos** [comment]
https://github.com/zquestz/bitcoincash/pull/75

**Pull request merged**
